package com.lyhq.center.dao.mapper;

import com.lyhq.center.dao.entity.LyhqTable;
import com.lyhq.center.dao.entity.LyhqTableExample;

import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LyhqTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyhq_table
     *
     * @mbggenerated Wed Jul 20 01:22:03 CST 2016
     */
    int countByExample(LyhqTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyhq_table
     *
     * @mbggenerated Wed Jul 20 01:22:03 CST 2016
     */
    int deleteByExample(LyhqTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyhq_table
     *
     * @mbggenerated Wed Jul 20 01:22:03 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyhq_table
     *
     * @mbggenerated Wed Jul 20 01:22:03 CST 2016
     */
    int insert(LyhqTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyhq_table
     *
     * @mbggenerated Wed Jul 20 01:22:03 CST 2016
     */
    int insertSelective(LyhqTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyhq_table
     *
     * @mbggenerated Wed Jul 20 01:22:03 CST 2016
     */
    List<LyhqTable> selectByExample(LyhqTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyhq_table
     *
     * @mbggenerated Wed Jul 20 01:22:03 CST 2016
     */
    LyhqTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyhq_table
     *
     * @mbggenerated Wed Jul 20 01:22:03 CST 2016
     */
    int updateByExampleSelective(@Param("record") LyhqTable record, @Param("example") LyhqTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyhq_table
     *
     * @mbggenerated Wed Jul 20 01:22:03 CST 2016
     */
    int updateByExample(@Param("record") LyhqTable record, @Param("example") LyhqTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyhq_table
     *
     * @mbggenerated Wed Jul 20 01:22:03 CST 2016
     */
    int updateByPrimaryKeySelective(LyhqTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyhq_table
     *
     * @mbggenerated Wed Jul 20 01:22:03 CST 2016
     */
    int updateByPrimaryKey(LyhqTable record);
}
